image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'

cache:
  paths:
    - .terraform

before_script:
  - terraform --version
  - terraform init

stages:
  - azlogin
  - validate
  - plan
  - apply

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan

apply:
  stage: apply
  script:
    - terraform apply
    - "yes"