image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'

variables:
  PLAN: plan.tfplan

cache:
  paths:
    - .terraform

before_script:
  - terraform --version
  - terraform init

stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:

build:
  stage: plan
  script:
    - terraform plan 

apply:
  stage: apply
  script:
    - terraform apply